name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: x64
          cache: 'maven'

      - name: Install Maven
        run: |
         sudo apt-get update
         sudo apt-get install -y maven

      - name: Tests
        run: mvn test -f pom.xml